@startuml
class Paypal [[java:edu.sru.cpsc.webshopping.domain.billing.Paypal]] {
	-id: long
	-paypalLogin: String
	-paypalPassword: String
	+getId(): long
	+setId(id: long): void
	+getPaypalLogin(): String
	+setPaypalLogin(paypalLogin: String): void
	+getPaypalPassword(): String
	+setPaypalPassword(paypalPassword: String): void
	+transferFields(other: Paypal): void
	+buildFromForm(other: Paypal_Form): void
}
@enduml