@startuml

  class TrackingController {
    - shippoTrackingService: ShippoTrackingService
    - transController: TransactionController
    + getTrackingInformation(transId: long): TrackDTO
  }

@enduml
