@startuml

class BankAddress_Form [[java:edu.sru.cpsc.webshopping.domain.billing.BankAddress_Form]] {
	-bankName: String
	-streetAddress: String
	-extraLocationInfo: String
	-postalCode: String
	-state: StateDetails
	-city: String
	+getBankName(): String
	+setBankName(bankName: String): void
	+getStreetAddress(): String
	+setStreetAddress(streetAddress: String): void
	+getExtraLocationInfo(): String
	+setExtraLocationInfo(extraLocationInfo: String): void
	+getPostalCode(): String
	+setPostalCode(postalCode: String): void
	+getState(): StateDetails
	+setState(selectedState: StateDetails): void
	+getCity(): String
	+setCity(city: String): void
}

@enduml