@startuml
class TaxExcelToDatabaseService [[java:edu.sru.cpsc.webshopping.service.TaxExcelToDatabaseService]] {
	-taxDetailRepository: StateDetailsRepository
	+loadFromExcelFile(excelFile: Resource): void
}
@enduml