@startuml
class TrackingEventDTO [[java:edu.sru.cpsc.webshopping.service.shipping.TrackingEventDTO]] {
	-objectCreated: String
	-objectId: String
	-status: String
	-statusDetails: String
	-statusDate: String
	-location: AddressDTO
	+getObjectCreated(): String
	+setObjectCreated(objectCreated: String): void
	+getObjectId(): String
	+setObjectId(objectId: String): void
	+getStatus(): String
	+setStatus(status: String): void
	+getStatusDetails(): String
	+setStatusDetails(statusDetails: String): void
	+getStatusDate(): String
	+setStatusDate(statusDate: String): void
	+getLocation(): AddressDTO
	+setLocation(location: AddressDTO): void
}
@enduml