@startuml Purchase Listing Use Case Diagram
title Purchase Listing Use Case Diagram
left to right direction

actor User as user
actor Database as db
actor Stripe as stripe

package Offerly {
usecase "Browse Listings" as browse
usecase "Search Listings" as search
usecase "View Listing" as view
usecase "Purchase Listing" as purchase
usecase "Add New Credit Card" as addCard
usecase "Add New Shipping Address" as addAddress
usecase "Add Billing Address" as addBilling
}

user ---> browse
browse ---> view
search ---> view
browse ---> search : <<extends>>
view ---> purchase
purchase ---> addCard : <<includes>>
purchase ---> addAddress : <<includes>>
purchase ---> addBilling : <<includes>>
addCard ---> stripe
addAddress ---> db
addBilling ---> stripe
purchase ---> db

@enduml