@startuml
class UserService [[java:edu.sru.cpsc.webshopping.service.UserService]] {
	-userRepository: UserRepository
	-userController: UserController
	+UserService(userRepository: UserRepository)
	+updateUserProfile(userId: Long, user: User): User
	+addUser(user: User): User
	+deleteUser(userId: Long): void
	+getUserById(userId: Long): User
	+getUserByUsername(username: String): User
	+rateUser(userId: Long, rating: float): User
	+getAllUsers(): List<User>
	+searchUsers(query: String, filterType: String): List<User>
}
@enduml