@startuml
class ImagePacketController [[java:edu.sru.cpsc.webshopping.controller.ImagePacketController]] {
	-packetRepo: ImagePacketRepository
	~ImagePacketController(packetRepo: ImagePacketRepository)
	+getImagePacketById(id: Long): ImagePacket
}
@enduml