@startuml

class StateDetailsController {
    - stateDetailsRepository : StateDetailsRepository

    + getAllStates() : Iterable<StateDetails>
    + getState(stateId : String) : StateDetails
}

@enduml
