@startuml
class PaymentService [[java:edu.sru.cpsc.webshopping.service.PaymentService]] {
	-directDepositDetailsRepository: DirectDepositDetailsRepository
	+getDirectDepositDetails(id: long): DirectDepositDetails
}
@enduml